package grails.example

import grails.plugins.rest.client.RestBuilder
import grails.test.mixin.integration.Integration
import org.springframework.beans.factory.annotation.Value
import org.springframework.http.HttpStatus
import spock.lang.Shared
import spock.lang.Specification

@Integration
class CustomJsonApiIdGeneratorSpecSpec extends Specification {

    @Shared
    @Value('${local.server.port}')
    int serverPort

    @Shared
    def rest = new RestBuilder()

    void "test custom id generation by type"() {
        when: 'an article is rendered'
        def resp = rest.get("http://localhost:${serverPort}/articles/1.json")
        def contentType = resp.headers.getContentType()

        then: 'the response attributes are as expected'
        resp.status == HttpStatus.OK.value()
        contentType.subtype == 'json'
        contentType.type == 'application'

        and: '1 article is represented in the json'
        resp.json.size() == 1

        and: 'the person id is the default value generated by ExampleJsonApiIdGenerator'
        resp.json.data.relationships.author.data.id == 'default-id-1'

        and: 'the person id is the Article specific value generated by ExampleJsonApiIdGenerator'
        resp.json.data.id == 'custom-article-id-1'
    }
}
